import { Geist, Geist_Mono, Roboto, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import "antd/dist/reset.css";



const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["500", "700"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={` ${oswald.className} ${oswald.variable} antialiased font-medium`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
