const enProjects = [
  {
    id: 1,
    slug: "proje-1",
    title: "Job Hunter Assistant",
    summary: "Job Hunter Assistant is an AI-powered application developed for young people struggling with the job search process. You can easily track your applications, see how suitable you are for job postings, and identify areas where you are strong or lacking.",
    description:
      "Job Hunter Assistant is an AI-powered application developed for young people struggling with the job search process.",
    longdescPath: "/projects/jobhunter/job-hunter-asistant.md",
    cover: "/projects/jobhunter/jobhunter.png",
    screenshots: ["/projects/jobhunter/jobhunterss1.png", "/projects/jobhunter/jobhunterss2.png", "/projects/jobhunter/jobhunterss3.png", "/projects/jobhunter/jobhunterss4.png"],
    tags: ["Next.js", "Tailwind", "Node.js", "Supabase", "OpenAI", "React Native", "Chrome Extension"],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/job_hunter_assistant",
  },
  {
    id: 2,
    slug: "proje-2",
    title: "Project Name 2",
    summary: "Brief description: problem, solution, technologies",
    description:
      "A solution focused on scalable architecture, clean code, and user experience. Integrations and measurable outputs are listed.",
    longdesc: "",
    cover: "/globe.svg",
    screenshots: ["/globe.svg", "/window.svg"],
    tags: ["React", "API", "PostgreSQL"],
    live: "#",
    code: "#",
  },
  {
    id: 3,
    slug: "proje-3",
    title: "Project Name 3",
    summary: "Brief description: problem, solution, technologies",
    description:
      "A project enriched with real-time features, caching, and accessibility improvements.",
    longdesc: "",
    cover: "/window.svg",
    screenshots: ["/window.svg"],
    tags: ["WebSocket", "Redis", "A11y"],
    live: "#",
    code: "#",
  },
  {
    id: 4,
    slug: "proje-4",
    title: "Project Name 4",
    summary: "Brief description: problem, solution, technologies",
    description:
      "An application delivered with production quality through test-driven development and CI/CD.",
    longdesc: "",
    cover: "/globe.svg",
    screenshots: ["/globe.svg"],
    tags: ["CI/CD", "Testing", "Docker"],
    live: "#",
    code: "#",
  },
  {
    id: 5,
    slug: "proje-5",
    title: "Project Name 5",
    summary: "Brief description: problem, solution, technologies",
    description: "SEO, performance, and accessibility-focused front-end project.",
    longdesc: "",
    cover: "/window.svg",
    screenshots: ["/window.svg"],
    tags: ["SEO", "Lighthouse", "PWA"],
    live: "#",
    code: "#",
  },
  {
    id: 6,
    slug: "proje-6",
    title: "Project Name 6",
    summary: "Brief description: problem, solution, technologies",
    description: "Corporate interface based on design system and component library.",
    longdesc: "",
    cover: "/globe.svg",
    screenshots: ["/globe.svg"],
    tags: ["Design System", "Storybook", "Monorepo"],
    live: "#",
    code: "#",
  },
  {
    id: 7,
    slug: "proje-7",
    title: "Project Name 7",
    summary: "Brief description: problem, solution, technologies",
    description: "Corporate interface based on design system and component library.",
    cover: "/globe.svg",
    screenshots: ["/globe.svg"],
    tags: ["Design System", "Storybook", "Monorepo"],
    live: "#",
    code: "#",
  },
];

export default enProjects;
