const projects = [
  {
    id: 1,
    slug: "proje-1",
    title: "Job Hunter Assistant",
    summary: "Job Hunter Assistant, iş arama sürecinde zorlanan gençler için geliştirilen bir yapay zeka tabanlı uygulamadır. Başvurularınızı kolayca takip edebilir, iş ilanlarına ne kadar uygun olduğunuzu ve hangi alanlarda güçlü ya da eksik olduğunuzu görebilirsiniz.",
    description:
      "Job Hunter Assistant, iş arama sürecinde zorlanan gençler için geliştirilen bir yapay zeka tabanlı uygulamadır.",
    longdescPath: "/projects/jobhunter/job-hunter-asistant.md",
    cover: "/projects/jobhunter/jobhunter.png",
    screenshots: ["/projects/jobhunter/jobhunterss1.png", "/projects/jobhunter/jobhunterss2.png", "/projects/jobhunter/jobhunterss3.png", "/projects/jobhunter/jobhunterss4.png"],
    tags: ["Next.js", "Tailwind", "Node.js", "Supabase", "OpenAI", "React Native", "Chrome Extension"],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/job_hunter_assistant",
  },
  {
    id: 2,
    slug: "proje-2",
    title: "Proje Adı 2",
    summary: "Kısa açıklama: problem, çözüm, teknolojiler",
    description:
      "Ölçeklenebilir mimari, temiz kod ve kullanıcı deneyimi odaklı bir çözüm. Entegrasyonlar ve ölçülebilir çıktılar listelenir.",
    longdesc: "",
    cover: "/globe.svg",
    screenshots: ["/globe.svg", "/window.svg"],
    tags: ["React", "API", "PostgreSQL"],
    live: "#",
    code: "#",
  },
  {
    id: 3,
    slug: "proje-3",
    title: "Proje Adı 3",
    summary: "Kısa açıklama: problem, çözüm, teknolojiler",
    description:
      "Gerçek zamanlı özellikler, önbellekleme ve erişilebilirlik geliştirmeleriyle zenginleştirilmiş bir proje.",
    longdesc: "",
    cover: "/window.svg",
    screenshots: ["/window.svg"],
    tags: ["WebSocket", "Redis", "A11y"],
    live: "#",
    code: "#",
  },
  {
    id: 4,
    slug: "proje-4",
    title: "Proje Adı 4",
    summary: "Kısa açıklama: problem, çözüm, teknolojiler",
    description:
      "Test güdümlü geliştirme ve CI/CD ile üretim kalitesinde teslim edilen uygulama.",
    longdesc: "",
    cover: "/globe.svg",
    screenshots: ["/globe.svg"],
    tags: ["CI/CD", "Testing", "Docker"],
    live: "#",
    code: "#",
  },
  {
    id: 5,
    slug: "proje-5",
    title: "Proje Adı 5",
    summary: "Kısa açıklama: problem, çözüm, teknolojiler",
    description: "SEO, performans ve erişilebilirlik odaklı front-end projesi.",
    longdesc: "",
    cover: "/window.svg",
    screenshots: ["/window.svg"],
    tags: ["SEO", "Lighthouse", "PWA"],
    live: "#",
    code: "#",
  },
  {
    id: 6,
    slug: "proje-6",
    title: "Proje Adı 6",
    summary: "Kısa açıklama: problem, çözüm, teknolojiler",
    description: "Design system ve component library tabanlı kurumsal arayüz.",
    longdesc: "",
    cover: "/globe.svg",
    screenshots: ["/globe.svg"],
    tags: ["Design System", "Storybook", "Monorepo"],
    live: "#",
    code: "#",
  },
  {
    id: 7,
    slug: "proje-6",
    title: "Proje Adı 6",
    summary: "Kısa açıklama: problem, çözüm, teknolojiler",
    description: "Design system ve component library tabanlı kurumsal arayüz.",
    cover: "/globe.svg",
    screenshots: ["/globe.svg"],
    tags: ["Design System", "Storybook", "Monorepo"],
    live: "#",
    code: "#",
  },
];

export default projects;


