const trProjects = [
  {
    id: 1,
    slug: "proje-1",
    title: "Job Hunter Assistant",
    summary: "Job Hunter Assistant, iş arama sürecinde zorlanan gençler için geliştirilen bir yapay zeka tabanlı uygulamadır. Başvurularınızı kolayca takip edebilir, iş ilanlarına ne kadar uygun olduğunuzu ve hangi alanlarda güçlü ya da eksik olduğunuzu görebilirsiniz.",
    description:
      "Job Hunter Assistant, iş arama sürecinde zorlanan gençler için geliştirilen bir yapay zeka tabanlı uygulamadır.",
    longdescPath: "/projects/jobhunter/job-hunter-asistant.md",
    cover: "/projects/jobhunter/jobhunter.png",
    screenshots: ["/projects/jobhunter/jobhunterss1.png", "/projects/jobhunter/jobhunterss2.png", "/projects/jobhunter/jobhunterss3.png", "/projects/jobhunter/jobhunterss4.png"],
    tags: ["Next.js", "Tailwind", "Node.js", "Supabase", "OpenAI", "React Native", "Chrome Extension"],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/job_hunter_assistant",
  },
  {
    id: 2,
    slug: "proje-2",
    title: "ShopStack",
    summary: "ShopStack; ürün yönetimi, sepet ve sipariş süreçleri, kullanıcı yorumları ve güçlü bir admin paneli içeren tam kapsamlı bir e‑ticaret uygulamasıdır.",
    description:
      "ShopStack; ürün yönetimi, sepet ve sipariş süreçleri, kullanıcı yorumları ve güçlü bir admin paneli içeren tam kapsamlı bir e‑ticaret uygulamasıdır.",
    longdescPath: "/projects/shopstack/shopstack.md",
    cover: "/projects/shopstack/shopstack.png",
    screenshots: ["/projects/shopstack/shopstackss1.png", "/projects/shopstack/shopstackss2.png", "/projects/shopstack/shopstackss3.png", "/projects/shopstack/shopstackss4.png"],
    tags: [
      "Next.js",
      "React", 
      "TypeScript",
      "Node.js",
      "Express",
      "Mongoose",
      "MongoDB",
      "JWT",
      "Multer",
      "Nodemailer",
      "Winston",
      "Ant Design",
      "Tailwind CSS",
      "Chart.js",
      "Redis",
      "Docker",
    ],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/shopstack",
  },
  {
    id: 3,
    slug: "proje-3",
    title: "Iot System",
    summary: "Bu proje, fabrikalardaki IoT sensörlerinden gelen verileri MQTT protokolü üzerinden toplayan, bu verileri gerçek zamanlı yayınlayan, kullanıcı ve şirket yönetimi sağlayan, loglama ve güvenlik mekanizmaları içeren kapsamlı bir sistemdir.",
    description:
      "Gerçek zamanlı özellikler, önbellekleme ve erişilebilirlik geliştirmeleriyle zenginleştirilmiş bir proje.",
    longdescPath: "/projects/iot/iot.md",
    cover: "/projects/iot/iot.png",
    screenshots: ["/projects/iot/iotss1.png", "/projects/iot/iotss2.png"],
    tags: [
      "NestJS",
      "Node.js",
      "Supabase",
      "PostgreSQL",
      "EMQX Cloud",
      "MQTT",
      "Socket.io",
      "JWT",
      "Docker",
      "Google Cloud Run",
      "Next.js",
      "WebSocket",
      "TLS"
    ],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/IoT-Sensor-Monitor",
  },
  {
    id: 4,
    slug: "proje-4",
    title: "BurgerShop",
    summary: "Kullanıcılar online olarak sipariş verebilirken, işletme sahipleri bu siparişleri anlık olarak takip edebilir. Modern yazılım mimarileri kullanılarak hem kullanıcı deneyimi hem de teknik sürdürülebilirlik ön planda tutulmuştur.",
    description:
      "Gerçek zamanlı özellikler, önbellekleme ve erişilebilirlik geliştirmeleriyle zenginleştirilmiş bir proje.",
    longdescPath: "/projects/burger/burger.md",
    cover: "/projects/burger/burger.png",
    screenshots: ["/projects/burger/burgerss1.png", "/projects/burger/burgerss2.png", "/projects/burger/burgerss3.png", "/projects/burger/burgerss4.png"],
    tags: [
      "Node.js",
      "Express.js",
      "Supabase",
      "PostgreSQL",
      "JWT",
      "Redis",
      "Stripe API",
      "Kafka",
      "Socket.IO",
      "Microservices",
      "Next.js",
      "Tailwind CSS",
      "Ant Design",
      "Context API",
      "SSR"
    ],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/BurgerShop-Fullstack",
  },
  {
    id: 5,
    slug: "proje-5",
    title: "P2P Döviz",
    summary: "Modern ve güvenli bir P2P (Peer-to-Peer) döviz alım-satım platformu. Kullanıcılar USD, EUR ve TRY arasında doğrudan işlem yapabilir, alış-satış emirleri verebilir ve otomatik eşleşme sistemi ile hızlı işlemler gerçekleştirebilir.",
    description: "",
    longdescPath: "/projects/p2p/p2p.md",
    cover: "/projects/p2p/p2p.png",
    screenshots: ["/projects/p2p/p2p.png"],
    tags: [
      "Node.js",
      "Express.js",
      "Supabase",
      "PostgreSQL",
      "JWT",
      "RESTful API",
      "JSON"
    ],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/Banker_goko",
  },
  {
    id: 6,
    slug: "proje-6",
    title: "GorkeMarkt",
    summary: "Bu Proje Patika.dev/Newmind AI Fullstack Bootcamp için hazırlamış olduğum e-ticaret projesidir. Proje, backend, frontend ve microservices olmak üzere üç ana bileşenden oluşmaktadır. Her bir bileşen, modern teknolojiler kullanılarak geliştirilmiştir ve Docker ile kolayca çalıştırılabilir durumdadır.",
    description: "",
    longdescPath: "/projects/gorkemarkt/gorkemarkt.md",
    cover: "/projects/gorkemarkt/gorkemarkt.png",
    screenshots: ["/projects/gorkemarkt/gorkemarkt.png", "/projects/gorkemarkt/gorkemarktss1.png", "/projects/gorkemarkt/gorkemarktss2.png", "/projects/gorkemarkt/gorkemarktss3.png"],
    tags: [
      "Node.js",
      "Express",
      "MongoDB",
      "JWT",
      "Cloudinary",
      "Redis",
      "Kafka",
      "Zookeeper",
      "Elasticsearch",
      "Docker",
      "Docker Compose",
      "React",
      "Vite",
      "Ant Design",
      "Axios",
      "Microservices"
    ],
    live: "#",
    code: "https://github.com/GorkemKurtkaya/Final_Case_Newmind_E-Commerce",
  }
];

export default trProjects;
